<p style="text-align:center">
    <a href="https://skills.network/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkPY0221ENSkillsNetwork23455645-2022-01-01" target="_blank">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="200" alt="Skills Network Logo"  />
    </a>
</p>

# Peer Review Assignment - Data Engineer - Extract API Data

Estimated time needed: **20** minutes

## Objectives

In this part you will:

*   Collect exchange rate data using an API
*   Store the data as a CSV

For this lab, we are going to be using Python and several Python libraries. Some of these libraries might be installed in your lab environment or in SN Labs. Others may need to be installed by you. The cells below will install these libraries when executed.

In [ ]:
#!mamba install pandas==1.3.3 -y
#!mamba install requests==2.26.0 -y

## Imports

Import any additional libraries you may need here.

In [6]:
import requests
import pandas as pd
import requests
import json

## Extract Data Using an API

Using ExchangeRate-API we will extract currency exchange rate data. Use the below steps to get the access key and to get the data.

1.  Open the url : [https://exchangeratesapi.io/](https://exchangeratesapi.io/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkPY0221ENSkillsNetwork23455645-2022-01-01) and click on **Get Free API Key**.
2.  Subscribe for Free plan and Sign-in with the Google Account.
3.  Once the account is created you will be redirected to [https://apilayer.com](https://apilayer.com/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkPY0221ENSkillsNetwork23455645-2022-01-01) website.
4.  Now, click on the **user icon** and click **Account** as shown below:

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0221EN-SkillsNetwork/labs/module%206/Final%20Assignment/Images/account.png"/>

3.  Scroll down and you will get the API Key section. Copy the API key and use in the url in Question 1.

### Call the API

<b> Question 1</b> Using the `requests` library call the endpoint given above and save the text, remember the first few characters of the output:

In [13]:
# Write your code here
url = "https://api.apilayer.com/exchangerates_data/latest?base=EUR&apikey=SQd6AuCuDxMgGSBLyMbFQAbAX95CMnBH" #Make sure to change ******* to your API key.
response=requests.get(url).json()
response
#currency=json.loads(response.text)
#currency['rates']
#response

{'success': True,
 'timestamp': 1675459503,
 'base': 'EUR',
 'date': '2023-02-03',
 'rates': {'AED': 3.966503,
  'AFN': 97.738559,
  'ALL': 114.79404,
  'AMD': 428.173637,
  'ANG': 1.946203,
  'AOA': 544.728626,
  'ARS': 203.032271,
  'AUD': 1.559483,
  'AWG': 1.946585,
  'AZN': 1.840179,
  'BAM': 1.932498,
  'BBD': 2.180375,
  'BDT': 115.929093,
  'BGN': 1.955661,
  'BHD': 0.407059,
  'BIF': 2236.548375,
  'BMD': 1.079936,
  'BND': 1.415358,
  'BOB': 7.462247,
  'BRL': 5.563507,
  'BSD': 1.079862,
  'BTC': 4.6174016e-05,
  'BTN': 88.367958,
  'BWP': 13.756511,
  'BYN': 2.726284,
  'BYR': 21166.754298,
  'BZD': 2.176719,
  'CAD': 1.447709,
  'CDF': 2208.470418,
  'CHF': 0.999838,
  'CLF': 0.031187,
  'CLP': 860.547783,
  'CNY': 7.316682,
  'COP': 5073.001445,
  'CRC': 605.163589,
  'CUC': 1.079936,
  'CUP': 28.618316,
  'CVE': 108.949603,
  'CZK': 23.771781,
  'DJF': 191.92673,
  'DKK': 7.444013,
  'DOP': 61.153664,
  'DZD': 146.353411,
  'EGP': 32.683741,
  'ERN': 16.199047,
  'ETB': 57.972077,
  'EUR': 1,
  'FJD': 2.347825,
  'FKP': 0.880943,
  'GBP': 0.895899,
  'GEL': 2.840655,
  'GGP': 0.880943,
  'GHS': 13.228585,
  'GIP': 0.880943,
  'GMD': 65.876507,
  'GNF': 9296.756101,
  'GTQ': 8.477053,
  'GYD': 227.858957,
  'HKD': 8.475288,
  'HNL': 26.622574,
  'HRK': 7.605126,
  'HTG': 161.945756,
  'HUF': 388.294431,
  'IDR': 16301.748613,
  'ILS': 3.691385,
  'IMP': 0.880943,
  'INR': 89.08245,
  'IQD': 1576.141618,
  'IRR': 45573.318309,
  'ISK': 153.502583,
  'JEP': 0.880943,
  'JMD': 166.846989,
  'JOD': 0.766111,
  'JPY': 141.669345,
  'KES': 134.722487,
  'KGS': 93.144934,
  'KHR': 4438.456376,
  'KMF': 487.379417,
  'KPW': 971.916281,
  'KRW': 1348.304745,
  'KWD': 0.329435,
  'KYD': 0.899964,
  'KZT': 494.638014,
  'LAK': 18186.910709,
  'LBP': 16221.5172,
  'LKR': 394.169688,
  'LRD': 169.496437,
  'LSL': 18.456526,
  'LTL': 3.188772,
  'LVL': 0.653243,
  'LYD': 5.109214,
  'MAD': 10.9745,
  'MDL': 20.269379,
  'MGA': 4611.858962,
  'MKD': 60.879969,
  'MMK': 2267.825229,
  'MNT': 3777.040378,
  'MOP': 8.726721,
  'MRO': 385.537125,
  'MUR': 49.007925,
  'MVR': 16.577433,
  'MWK': 1108.396829,
  'MXN': 20.482205,
  'MYR': 4.598411,
  'MZN': 68.932751,
  'NAD': 18.456521,
  'NGN': 497.354337,
  'NIO': 39.458599,
  'NOK': 11.033499,
  'NPR': 141.388535,
  'NZD': 1.70687,
  'OMR': 0.415728,
  'PAB': 1.079862,
  'PEN': 4.133187,
  'PGK': 3.805972,
  'PHP': 58.576158,
  'PKR': 297.52649,
  'PLN': 4.718102,
  'PYG': 7892.071267,
  'QAR': 3.93209,
  'RON': 4.895572,
  'RSD': 117.329736,
  'RUB': 76.139504,
  'RWF': 1169.104873,
  'SAR': 4.052282,
  'SBD': 8.852533,
  'SCR': 15.170191,
  'SDG': 631.226824,
  'SEK': 11.386638,
  'SGD': 1.429192,
  'SHP': 1.487509,
  'SLE': 21.467898,
  'SLL': 21004.764197,
  'SOS': 613.947826,
  'SRD': 34.864709,
  'STD': 22352.504003,
  'SVC': 9.448919,
  'SYP': 2713.380111,
  'SZL': 18.516739,
  'THB': 36.124273,
  'TJS': 11.139014,
  'TMT': 3.790577,
  'TND': 3.283551,
  'TOP': 2.496759,
  'TRY': 20.336721,
  'TTD': 7.329643,
  'TWD': 32.378551,
  'TZS': 2525.971704,
  'UAH': 39.884556,
  'UGX': 3978.268582,
  'USD': 1.079936,
  'UYU': 41.807242,
  'UZS': 12221.089317,
  'VEF': 2420059.465024,
  'VES': 24.463205,
  'VND': 25324.509607,
  'VUV': 124.168895,
  'WST': 2.879369,
  'XAF': 648.15257,
  'XAG': 0.04829,
  'XAU': 0.000579,
  'XCD': 2.918583,
  'XDR': 0.79562,
  'XOF': 648.131814,
  'XPF': 118.393825,
  'YER': 270.419966,
  'ZAR': 18.867052,
  'ZMK': 9720.727793,
  'ZMW': 20.631111,
  'ZWL': 347.739094}}

### Save as DataFrame

<b> Question 2</b>  Using the data gathered turn it into a `pandas` dataframe. The dataframe should have the Currency as the index and `Rate` as their columns. Make sure to drop unnecessary columns.

In [16]:
# Turn the data into a dataframe
df= pd.DataFrame.from_dict(response)

In [17]:
df

     success   timestamp base        date        rates
AED     True  1675459503  EUR  2023-02-03     3.966503
AFN     True  1675459503  EUR  2023-02-03    97.738559
ALL     True  1675459503  EUR  2023-02-03   114.794040
AMD     True  1675459503  EUR  2023-02-03   428.173637
ANG     True  1675459503  EUR  2023-02-03     1.946203
..       ...         ...  ...         ...          ...
YER     True  1675459503  EUR  2023-02-03   270.419966
ZAR     True  1675459503  EUR  2023-02-03    18.867052
ZMK     True  1675459503  EUR  2023-02-03  9720.727793
ZMW     True  1675459503  EUR  2023-02-03    20.631111
ZWL     True  1675459503  EUR  2023-02-03   347.739094

[170 rows x 5 columns]

In [18]:
# Drop unnescessary columns
df=df.drop(columns=['success','timestamp','base','date'])

In [19]:
df.index

           rates
AED     3.966503
AFN    97.738559
ALL   114.794040
AMD   428.173637
ANG     1.946203
..           ...
YER   270.419966
ZAR    18.867052
ZMK  9720.727793
ZMW    20.631111
ZWL   347.739094

[170 rows x 1 columns]

### Load the Data

Using the dataframe save it as a CSV names `exchange_rates_1.csv`.

In [20]:
# Save the Dataframe
df.to_csv('exchange_rates_1.csv')

Your CSV should be in this format with more currencies

|     | Rates      |
| --- | ---------- |
| AED | 4.398618   |
| AFN | 92.917693  |
| ALL | 123.099093 |
| AMD | 621.935674 |
| ANG | 2.149648   |

## Authors

Ramesh Sannareddy, Joseph Santarcangelo and Azim Hirjani

### Other Contributors

In [ ]:
import zipfile
with zipfile.ZipFile('source.zip', 'r') as file:
    file.extractall()

Rav Ahuja

## Change Log

| Date (YYYY-MM-DD) | Version | Changed By        | Change Description                              |
| ----------------- | ------- | ----------------- | ----------------------------------------------- |
| 2022-05-06        | 0.3     | Malika            | Updated instructions to get the API and the url |
| 2021-04-15        | 0.2     | Malika            | Updated the lab from USD to EUR                 |
| 2020-11-25        | 0.1     | Ramesh Sannareddy | Created initial version of the lab              |

Copyright © 2020 IBM Corporation. This notebook and its source code are released under the terms of the [MIT License](https://cognitiveclass.ai/mit-license?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkPY0221ENSkillsNetwork23455645-2022-01-01&cm_mmc=Email_Newsletter-\_-Developer_Ed%2BTech-\_-WW_WW-\_-SkillsNetwork-Courses-IBM-DA0321EN-SkillsNetwork-21426264&cm_mmca1=000026UJ&cm_mmca2=10006555&cm_mmca3=M12345678&cvosrc=email.Newsletter.M12345678&cvo_campaign=000026UJ).